apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: example-chart
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: example-chart
  targetCPUUtilizationPercentage: 50
